export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const EDIT_FAILURE = 'EDIT_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const USER_STATEMENT = 'USER_STATEMENT';